AWSTemplateFormatVersion: 2010-09-09
Description: EKS Cluster

Parameters:
  VpcId:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
  ClusterRoleArn:
    Type: String

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: my-eks
      RoleArn: !Ref ClusterRoleArn
      Version: "1.33"
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2
        EndpointPublicAccess: true

Outputs:
  ClusterName:
    Value: !Ref EKSCluster
