AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ClusterName:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
  NodeRoleArn:
    Type: String

Resources:
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref ClusterName
      NodeRole: !Ref NodeRoleArn
      ScalingConfig:
        DesiredSize: 1
        MinSize: 1
        MaxSize: 2
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      AmiType: AL2023_x86_64_STANDARD
      InstanceTypes:
        - t2.micro
